version: '3'
services:
  web:
    image: howie6879/owllook
    command: pipenv run gunicorn -c soulbook/config/gunicorn.py --worker-class sanic.worker.GunicornWorker soulbook.server:app
    ports:
     - "8001:8001"
    volumes:
     - .:/soulbook